name: Run raytracer and commit generated image

on:
  workflow_dispatch: # allows manual trigger
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  update-generated-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed so this job can push to main
      
      - name: Build
        run: cargo build --verbose

      - name: Generate image
        run: |
          cargo run -- verbose

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update generated image."
            git push
          fi
